#!/usr/bin/ruby

require "pp"
require "net/http"
require "net/smtp"
require "uri"
require "nokogiri"
require "cgi"
require "etc"
require "trollop"
require 'open-uri'

home = Etc.getpwuid(Process.uid).dir
$footer_msg = "-- If they won't invite you in, <a href='http://38.media.tumblr.com/tumblr_lk65pfPql21qzi80do1_500.gif'>kick down the door</a>."
$admin_addr = "stange@johnstange.net"
$recips = [$admin_addr]
if File.exists?("#{home}/.audition_recips")
  File.open("#{home}/.audition_recips", "r").each_line { |line|
    $recips << line.chomp if line.match(/@/)
  }
end

$opts = Trollop::options do
  banner <<-EOS
Usage:
#{$0} [-a]
  EOS
  opt :all, "Show all harvested notices, instead of just new ones.", :require => false, :default => false, :type => :boolean
end

if File.exists?("#{home}/.notice_cache")
  $notices = Marshal.load(File.read("#{home}/.notice_cache"))
else
  $notices = {}
end

$runtime = Time.new

def formpost(uri, params)
  response = Net::HTTP.post_form(uri, params)
  if response.code == "302"
    return Net::HTTP.get(URI.parse(response['location']))
  elsif response.code == "200"
    return response.body
  else
    puts "Error formposting #{uri.to_s}: #{response.inspect}"
  end
  return nil
end

def scrape_playbill
  ["MD", "DC", "VA"].each { |state|
    uri = URI.parse("http://www.playbill.com/job/listing")
    uri.query = "q=&category=Performer&date=&state=#{state}&paid=on"
    body = Net::HTTP.get_response(uri).body
    html_doc = Nokogiri::HTML(body)
    html_doc.css("table.bsp-table tr").each { |listing|
      titlelink = listing.children.first.css("a span").text
      namestr = "Playbill - #{CGI.unescapeHTML(titlelink.to_s)}"
      if !$notices.has_key?(namestr)
        $notices[namestr] = {}
        $notices[namestr]['firstseen'] = $runtime
      end
      $notices[namestr]['url'] = "http://www.playbill.com"+listing.children.first.css("a").first.attributes['href']
      $notices[namestr]['lastseen'] = $runtime
    }
  }
end

def scrape_actorsequity
  uri = URI.parse("http://www.actorsequity.org/CastingCall/search_auditions.asp")
  params = {
    "NoticeType" => "1",
    "CallType" => "0",
    "Region" => "01",
    "Contract" => "0"
  }
  body = formpost(uri, params)

  html_doc = Nokogiri::HTML(body)
  html_doc.css("p.cc_headline").each { |listing|
    catch (:wrongstate) do
      listing.children.each { |elt|
        if elt.class == Nokogiri::XML::Text
          if CGI.unescapeHTML(elt.to_s).match(/&nbsp;in&nbsp;.*?, [A-Z]{2}$/)
            throw :wrongstate if !elt.to_s.match(/ (DC|MD|VA)$/)
          end
        elsif elt.class == Nokogiri::XML::Element and elt.attributes.has_key?("href")
          namestr = "AEA - #{CGI.unescapeHTML(elt.children.first.to_s)}"
          if !$notices.has_key?(namestr)
            $notices[namestr] = {}
            $notices[namestr]['firstseen'] = $runtime
          end
          $notices[namestr]['url'] = "http://www.actorsequity.org/CastingCall/"+elt.attributes['href'].value
          $notices[namestr]['lastseen'] = $runtime
        end
      }
    end
  }
end

def scrape_backstage
  uri = URI.parse("https://www.backstage.com/casting/")
  uri.query = "gender=B&min_age=0&max_age=99&pt=55&pt=60&pt=69&pt=70&compensation=true&union_status=&location=Washington%2C+DC&geo=-77.03687070000001%2C38.9071923&radius=50.0&exclude_nationwide=true&q=&sort_by=newest&page=1"
  body = open(uri.to_s).read
  html_doc = Nokogiri::HTML(body)
  html_doc.css("a.callLink").each { |listing|
    namestr = "Backstage - #{CGI.unescapeHTML(listing.children.first.children.first.to_s)}"
    if !$notices.has_key?(namestr)
      $notices[namestr] = {}
      $notices[namestr]['firstseen'] = $runtime
    end
    $notices[namestr]['url'] = listing.attributes['href'].value
    $notices[namestr]['url'] = "http://www.backstage.com/"+$notices[namestr]['url'] if !$notices[namestr]['url'].match(/^http/)
    $notices[namestr]['lastseen'] = $runtime
  }
end

scrape_playbill
scrape_actorsequity
scrape_backstage


# Scrub anything that no longer shows up
deletia = []
$notices.each_pair { |name, data|
  deletia << name if data['lastseen'] < $runtime
}
deletia.each { |defunct|
  $notices.delete(defunct)
}

File.open("#{home}/.notice_cache", 'w') { |file|
  file.write Marshal.dump($notices)
}

msg_body = ""
keys = $notices.each_key.sort { |a, b|
  if $notices[a]['firstseen'] == $notices[b]['firstseen']
    val = a <=> b
  else
    val = $notices[b]['firstseen'] <=> $notices[a]['firstseen']
  end
}
count = 0

keys.each { |name|
  data = $notices[name]
  next if !$opts[:all] and data['firstseen'] != $runtime
  count = count + 1
  msg_body = msg_body + "<p>"
  if data['firstseen'].to_s == $runtime.to_s
    msg_body = msg_body + "NEW: "
  end
  msg_body = msg_body + "<a href='#{data['url']}'>#{name}</a></p>\n"
}
exit if count == 0

message = <<MESSAGE_END
From: #{$admin_addr}
To: #{$admin_addr}
MIME-Version: 1.0
Subject: Wack-Ass Equity Audition Postings
Content-type: text/html
    

#{msg_body}

#{$footer_msg}
MESSAGE_END

puts message
Net::SMTP.start('localhost') { |smtp|
  smtp.send_message message, $admin_addr, $recips
}
